- path: output/Mail@domain.mrs
  format: mrs
  behavior: domain
  upstream:
    A:
      type: http
      url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Mail/Mail.yaml"
      format: yaml
      behavior: domain

- path: output/Apple@domain.mrs
  format: mrs
  behavior: domain
  upstream:
    A:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
      format: text
      behavior: domain
    B:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
      format: text
      behavior: domain

- path: output/Direct@domain.mrs
  format: mrs
  behavior: domain
  upstream:
    A:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
      format: text
      behavior: domain
    B:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
      format: text
      behavior: domain

- path: output/Proxy@domain.mrs
  format: mrs
  behavior: domain
  upstream:
    A:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
      format: text
      behavior: domain
    B:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
      format: text
      behavior: domain
    C:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
      format: text
      behavior: domain
    D:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
      format: text
      behavior: domain

- path: output/Direct@ipcidr.mrs
  format: mrs
  behavior: ipcidr
  upstream:
    A:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
      format: text
      behavior: ipcidr
    B:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
      format: text
      behavior: ipcidr

- path: output/Telegram@ipcidr.mrs
  format: mrs
  behavior: ipcidr
  upstream:
    A:
      type: http
      url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
      format: text
      behavior: ipcidr
