- path: output/AdBlock.yaml
  format: yaml
  behavior: classical
  upstream:
    A:
      type: http
      url: "https://raw.githubusercontent.com/CodeWithMyLife/config/refs/heads/master/OPPO.yaml"
      format: yaml
      behavior: classical

    B:
      type: http
      url: "https://github.com/CodeWithMyLife/AdBlock_Rule_For_Clash/raw/refs/heads/main/adblock_reject.yaml"
      format: yaml
      behavior: classical

    C:
      type: http
      url: "https://github.com/REIJI007/AdBlock_Rule_For_Clash/raw/refs/heads/main/adblock_reject.yaml"
      format: yaml
      behavior: classical

    D:
      type: http
      url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising.yaml"
      format: yaml
      behavior: classical

    E:
      type: http
      url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical.yaml"
      format: yaml
      behavior: classical
